import numpy as np
print("Please select an operation:")
print("1.Addition")
print("2.Subtraction")
print("3.Multiplication")
print("4.Division")
print("5.Square root")
print("6.Exponentiation")
print("7.Logarithm")
print("8.Trigonometric functions")
print("9.Exit")
option=int(input())
while option!=9:
  if option==1:
    num1=float(input("Enter first number:"))
    num2=float(input("Enter second number:"))
    result=np.add(num1,num2)
    print("Result:",result)
  elif option==2:
    num1=float(input("Enter first number:"))
    num2=float(input("Enter second number:"))
    result=np.subtract(num1,num2)
    print("Result:",result)
  elif option==3:
    num1=float(input("Enter first number:"))
    num2=float(input("Enter second number:"))
    result=np.multiplication(num1,num2)
    print("Result:",result)
  elif option==4:
    num1=float(input("Enter numerator:"))
    num2=float(input("Enter denominator:"))
    result=np.divsion(num1,num2)
    print("Result:",result)
  elif option==5:
    num=float(input("Enter numbere:"))
    result=np.sqrt(num)
    print("Result:",result)
  elif option==6:
    num1=float(input("Enter base:"))
    num2=float(input("Enter exponent:"))
    result=np.power(num1,num2)
    print("Result:",result)
  elif option==7:
    num=float(input("Enter numbere:"))
    result=np.log10(num)
    print("Result:",result)
  elif option==8:
    num=float(input("Enter angle in degrees:"))
    sin_result=np.sin(np.radians(num))
    cos_result=np.cos(np.radians(num))
    tan_result=np.tan(np.radians(num))
    print("Sine:",sin_result)
    print("Cosine:",cos_result)
    print("Tangent:",tan_result)
  else:
    print("Invalid option")
  print("Please select an operation:")
  print("1.Addition")
  print("2.Subtraction")
  print("3.Multiplication")
  print("4.Division")
  print("5.Square root")
  print("6.Exponentiation")
  print("7.Logarithm")
  print("8.Trigonometric functions")
  print("9.Exit")
  option=int(input())
print("Thankyou for using our scientic calculator")
